version: 1
disable_existing_loggers: false

formatters:
  test:
    format: '%(levelname)s - %(name)s - %(message)s'

handlers:
  test_console:
    class: logging.StreamHandler
    level: WARNING
    formatter: test
    stream: ext://sys.stderr

loggers:
  wct:
    level: WARNING
    handlers: [test_console]
    propagate: false

root:
  level: ERROR
  handlers: [test_console]
