version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  rich_console:
    class: rich.logging.RichHandler
    level: INFO
    formatter: standard
    markup: true
    rich_tracebacks: true
    tracebacks_show_locals: false
    show_time: true
    show_path: false

loggers:
  wct:
    level: INFO
    handlers: [rich_console]
    propagate: false

  wct.executor:
    level: INFO
    handlers: [rich_console]
    propagate: false

  wct.connectors:
    level: INFO
    handlers: [rich_console]
    propagate: false

  wct.analysers:
    level: INFO
    handlers: [rich_console]
    propagate: false

  wct.rulesets:
    level: INFO
    handlers: [rich_console]
    propagate: false

  wct.cli:
    level: INFO
    handlers: [rich_console]
    propagate: false

root:
  level: WARNING
  handlers: [rich_console]
