"""Types for connector-generated data.

This module contains base metadata classes used by connectors to provide
context about the data they extract. All connector output should include
metadata extending BaseMetadata for proper schema routing and analysis.
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, Field, field_validator


class BaseMetadata(BaseModel):
    """Base metadata class for all WCT-connector generated data.

    All WCT schemas compliant data generated by connectors must
    include source identification (this is required for all input data)
    and connector type for proper schema routing and analysis.
    """

    source: str = Field(description="Source identifier for the data item")
    connector_type: str = Field(
        description="Type of connector that generated this data point"
    )
    context: dict[str, Any] = Field(
        default_factory=dict,
        description="Extensible context for pipeline metadata (artifact_id, etc.)",
    )

    @field_validator("context")
    @classmethod
    def validate_json_serialisable(cls, v: dict[str, Any]) -> dict[str, Any]:
        """Ensure context is JSON-serialisable for portable storage."""
        try:
            json.dumps(v)
        except (TypeError, ValueError) as e:
            raise ValueError(f"context must be JSON-serialisable: {e}") from e
        return v


class RelationalDatabaseMetadata(BaseMetadata):
    """Metadata for data generated by relational database connectors (MySQL, PostgreSQL, etc.).

    Provides specific relational database context for data subject classification
    and compliance analysis.
    """

    table_name: str = Field(description="Name of the database table")
    column_name: str = Field(description="Name of the database column")
    schema_name: str = Field(description="Name of the database schema")


class FilesystemMetadata(BaseMetadata):
    """Metadata for data generated by filesystem connectors.

    Provides file context for data subject classification
    and compliance analysis in file-based data sources.
    """

    file_path: str = Field(description="Path to the source file")
