name: "Nested Configuration Example"
description: >
  Example demonstrating the new strongly typed nested configuration approach
  for better separation of concerns between different runner types.

connectors:
  - name: "sample_filesystem"
    type: "filesystem"
    properties:
      path: "./tests/wct/connectors/filesystem/"
      file_patterns: ["*.txt"]
      max_file_size: 1048576  # 1MB
      include_hidden_files: false

analysers:
  - name: "personal_data_analyser_nested_config"
    type: "personal_data_analyser"
    properties:
      # Pattern matching runner configuration
      pattern_matching:
        ruleset: "personal_data"
        evidence_context_size: "medium"
        maximum_evidence_count: 5

      # LLM validation runner configuration
      llm_validation:
        enable_llm_validation: false  # Disabled for demo
        llm_batch_size: 25
        llm_validation_mode: "conservative"

execution:
  - connector: "sample_filesystem"
    analyser: "personal_data_analyser_nested_config"
    input_schema_name: "standard_input"
    output_schema_name: "personal_data_finding"
    context:
      description: "Test nested configuration approach"
