services:
  mysql:
    image: mysql:8.0
    container_name: waivern_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - waivern_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "-prootpassword",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    image: wordpress:6.4-php8.2-apache
    container_name: waivern_wordpress
    depends_on:
      mysql:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
    volumes:
      - wordpress_data:/var/www/html
      - ./plugins:/tmp/plugins
      - ./scripts/entrypoint.sh:/usr/local/bin/custom-entrypoint.sh
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    networks:
      - waivern_network
    entrypoint: ["/usr/local/bin/custom-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/install.php"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:
  wordpress_data:

networks:
  waivern_network:
    driver: bridge
