# Organisation Configuration
# This file contains metadata about your organisation for privacy document generation.
# Non-technical users can easily edit this file to update organisation information.

data_controller:
  name: "Waivern Ltd"
  company_nr: "16345663802"
  address: "Solbakken Alle 24D, 1086, Oslo, Norway"
  contact_email: "info@waivern.com"
  trading_name: ""  # Leave empty if same as company name
  jurisdictions:
    - "EU"
    - "UK"

# Optional
joint_controller:
  name: "Jean Dow"
  processing_purposes: "Personal Data Collection"
  contact_email: "jean.dow@waivern.com"
  contact_address: "Solbakken Alle 24D, 1086, Oslo, Norway"

# Optional - List of representatives for different jurisdictions
representatives:
  - company_name: "John Dow"
    company_jurisdiction: "UK"  # This representative serves UK jurisdiction
    contact_email: "john.dow@waivern.com"
    contact_address: "21 East Street, London, UK"
    representative_jurisdiction: "UK"  # Representative is located in UK

dpo:
  name: "Vincent G Nunan"
  contact_email: "vincent.nunan@waivern.com"
  contact_address: "Solbakken Alle 24D, 1086, Oslo"

privacy_contact:
  email: "info@waivern.com"

data_retention:
  general_rule: "18 months from creation"
  exceptions:
    financial_records: "6 years (legal obligation)"
