name: CI

on:
  pull_request: {}
  push:
    branches: [main]

concurrency:
  # Cancel existing workflows in pull requests to save on costs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  code-quality:
    name: Code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: ./scripts/init.sh

      - name: Run CI quality checks
        run: ./scripts/ci-checks.sh

  test:
    name: Test with Python ${{ matrix.python-version }} on ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          # - "3.11"
          # - "3.13"
        runner:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: ./scripts/init.sh

      - name: Test
        run: ./scripts/test.sh

      - name: Generate WCT CLI artifacts
        run: |
          mkdir -p ci_artifacts
          uv run wct run runbooks/samples/LAMP_stack_lite.yaml --output-dir ci_artifacts/lamp_stack_lite
          uv run wct run runbooks/samples/file_content_analysis.yaml --output-dir ci_artifacts/file_content_analysis
        continue-on-error: true

      - name: Upload WCT CLI artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wct-cli-outputs-${{ matrix.python-version }}-${{ matrix.runner }}
          path: ci_artifacts/
          retention-days: 30
