name: CI

on:
  pull_request: {}
  push:
    branches: [main]

concurrency:
  # Cancel existing workflows in pull requests to save on costs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check formatting
        run: uv run --dev ruff format --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Lint
        run: uv run --dev ruff check

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Type check
        run: uv run --dev mypy

  test:
    name: Test with Python ${{ matrix.python-version }} on ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: uv run --dev pytest
