name: CI

on:
  pull_request: {}
  push:
    branches: [main]

concurrency:
  # Cancel existing workflows in pull requests to save on costs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  checks:
    name: Python check ${{ matrix.check.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        check:
          - name: linting
            run: uv run --dev ruff check
          - name: formatting
            run: uv run --dev ruff format --check
          - name: types
            run: uv run --dev mypy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run ${{ matrix.check.name }} checks
        run: ${{ matrix.check.run }}

  test:
    name: Test with Python ${{ matrix.python-version }} on ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: uv run --dev pytest
